TRUNCATE TABLE [BEYBLADE_MATCH_MAKER]..[BITS]

INSERT INTO [BEYBLADE_MATCH_MAKER]..[BITS] VALUES
	(NEWID(), 'Flat', 'F'),
	(NEWID(), 'Taper', 'T'),
	(NEWID(), 'Ball', 'B'),
	(NEWID(), 'Needle', 'N'),
	(NEWID(), 'High Needle', 'HN'),
	(NEWID(), 'Low Flat', 'LF'),
	(NEWID(), 'Point', 'P'),
	(NEWID(), 'Orb', 'O'),
	(NEWID(), 'Spike', 'S'),
	(NEWID(), 'Rush', 'R'),
	(NEWID(), 'High Taper', 'HT'),
	(NEWID(), 'Gear Flat', 'GF'),
	(NEWID(), 'Gear Ball', 'GB'),
	(NEWID(), 'Gear Point', 'GP'),
	(NEWID(), 'Gear Needle', 'GN'),
	(NEWID(), 'Metal Needle', 'MN'),
	(NEWID(), 'Elevate', 'E'),
	(NEWID(), 'Hexa', 'H'),
	(NEWID(), 'Quake', 'Q'),
	(NEWID(), 'Accel', 'A'),
	(NEWID(), 'Disc Ball', 'DB'),
	(NEWID(), 'Unite', 'U'),
	(NEWID(), 'Cyclone', 'C'),
	(NEWID(), 'Dot', 'D'),
	(NEWID(), 'Glide', 'G')